site_name: Climate Dynamics Lab
repo_url: https://github.com/Climate-Dynamics-Lab/Wiki  # provides link to github repo
repo_name: Climate-Dynamics-Lab/Wiki

theme:
  name: material
  custom_dir: overrides       # So can download jupyter notebook pages
  # 404 page
  static_templates:
      - 404.html
  palette:
    primary: black   # specify colour of website
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.expand
    - content.tabs.link
    - navigation.sections
    # - toc.integrate  # This puts table of contents in right sidebar into left sidebar but makes left sidebar quite big
    - navigation.top
  font:
      text: Roboto
      code: Roboto Mono
  icon:
      logo: logo

plugins:
  - search
  - mkdocs-jupyter:
        ignore_h1_titles: false
        include_source: True
  - mkdocstrings:
        default_handler: python
        handlers:
          python:
            options:
              show_root_toc_entry: true # stops extra heading in contents of Code pages

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Climate-Dynamics-Lab/Wiki
      name: Github Repository

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js   # allows you to put use latex maths equations.
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: index.md
    - Contributing:
        - contributing/index.md
        - MkDocs: contributing/mkdocs.md
    - HPC Basics:
        - hpc_basics/index.md
        - Shell Scripting: hpc_basics/shell_scripting.md
        - Slurm: hpc_basics/slurm.md
        - Hypatia: hpc_basics/hypatia.md
        - Archer2: hpc_basics/archer2.md
        - JASMIN: hpc_basics/jasmin.md
    - Climate Models:
        - climate_models/index.md
        - Isca:
            - climate_models/isca/index.md
        - CESM:
            - climate_models/cesm/index.md
    - Data:
        - data/index.md
        - ERA5:
            - data/era5/index.md
        - CESM:
            - data/cesm/index.md
        - CMIP:
            - data/cmip/index.md
            - CEDA/ESGF: data/cmip/CEDAESGF_Wrapper.ipynb  # takes title from first #H1 heading